import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartIcon } from "@/ui/CartIcon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex items-end justify-end p-5">
          <CartIcon />
        </header>
        {children}
      </body>
    </html>
  );
}
